package com.example.android.childtracker.utils

object Constants {
    const val SEARCH_DATA_SYMBOL_LAYER_SOURCE_ID = "SEARCH_DATA_SYMBOL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_LINE_LAYER_SOURCE_ID = "FREEHAND_DRAW_LINE_LAYER_SOURCE_ID"
    const val MARKER_SYMBOL_LAYER_SOURCE_ID = "MARKER_SYMBOL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_FILL_LAYER_SOURCE_ID = "FREEHAND_DRAW_FILL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_LINE_LAYER_ID = "FREEHAND_DRAW_LINE_LAYER_ID"
    const val FREEHAND_DRAW_FILL_LAYER_ID = "FREEHAND_DRAW_FILL_LAYER_ID"
    const val SEARCH_DATA_SYMBOL_LAYER_ID = "SEARCH_DATA_SYMBOL_LAYER_ID"
    const val SEARCH_DATA_MARKER_ID = "SEARCH_DATA_MARKER_ID"
    const val LINE_COLOR = "#a0861c"
    const val LINE_WIDTH = 5f
    const val LINE_OPACITY = 1f
    const val FILL_OPACITY = .4f
    const val DEFAULT_INTERVAL_IN_MILLISECONDS = 1000L
    const val DEFAULT_MAX_WAIT_TIME = DEFAULT_INTERVAL_IN_MILLISECONDS * 5
    const val REQUEST_CODE_LOCATION_PERMISSION = 0
}