package com.example.android.childtracker.utils

object Constants {
    const val SEARCH_DATA_SYMBOL_LAYER_SOURCE_ID = "SEARCH_DATA_SYMBOL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_LINE_LAYER_SOURCE_ID = "FREEHAND_DRAW_LINE_LAYER_SOURCE_ID"
    const val MARKER_SYMBOL_LAYER_SOURCE_ID = "MARKER_SYMBOL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_FILL_LAYER_SOURCE_ID = "FREEHAND_DRAW_FILL_LAYER_SOURCE_ID"
    const val FREEHAND_DRAW_LINE_LAYER_ID = "FREEHAND_DRAW_LINE_LAYER_ID"
    const val FREEHAND_DRAW_FILL_LAYER_ID = "FREEHAND_DRAW_FILL_LAYER_ID"
    const val SEARCH_DATA_SYMBOL_LAYER_ID = "SEARCH_DATA_SYMBOL_LAYER_ID"
    const val SEARCH_DATA_MARKER_ID = "SEARCH_DATA_MARKER_ID"
    const val LINE_COLOR = "#a0861c"
    const val LINE_WIDTH = 5f
    const val LINE_OPACITY = 1f
    const val FILL_OPACITY = .4f
    const val DEFAULT_INTERVAL_IN_MILLISECONDS = 5000L
    const val DEFAULT_MAX_WAIT_TIME = DEFAULT_INTERVAL_IN_MILLISECONDS * 5
    const val REQUEST_CODE_LOCATION_PERMISSION = 0

    const val SOURCE_ID = "SOURCE_ID"
    const val ICON_ID = "ICON_ID"
    const val LAYER_ID = "LAYER_ID"

    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_CALL_SERVICE = "ACTION_CALL_SERVICE"
    const val ACTION_SMS_SERVICE = "ACTION_SMS_SERVICE"

    const val NOTIFICATION_CHANNEL_ID = "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking_child"
    const val NOTIFICATION_CHILD_ID = 1

    const val NOTIFICATION_CHILD_CHANNEL_ID = "tracking_channel_child"
    const val NOTIFICATION_CHILD_CHANNEL_NAME = "Tracking"
    const val NOTIFICATION_CHILD_SERVICE_ID = 2

    const val SHARED_PREFERENCE_FILE_NAME = "Profession"
    const val SHARED_PREFERENCE_KEY_NAME = "KEY"

    const val REQUEST_IMAGE_PICK = 0


}